name: pookiedex_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.0
  flex_color_scheme: ^7.3.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
