// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDL7wrd7T53gfmWQxRdUoPdg-2gsZcc8',
    appId: '1:1081233069513:android:b8f8f2f6b8ac638e2f8418',
    messagingSenderId: '1081233069513',
    projectId: 'gauth-test-96dd8',
    storageBucket: 'gauth-test-96dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yHY4Ssltw9jkoAEWtvap8A0vtvl0g7c',
    appId: '1:1081233069513:ios:6340660076870ad22f8418',
    messagingSenderId: '1081233069513',
    projectId: 'gauth-test-96dd8',
    storageBucket: 'gauth-test-96dd8.appspot.com',
    androidClientId: '1081233069513-07ecmqoh46es0gs2ua3fpvu0c15ehstt.apps.googleusercontent.com',
    iosClientId: '1081233069513-hjk17e30k9jmf79v4hh5crjg9b4fkjta.apps.googleusercontent.com',
    iosBundleId: 'com.pookiedex.com',
  );
}
